# Título y descripción de TU sitio
title: Sujetxs Criticxs 
description: Una descripción para tu sitio web.

# Tema
theme: just-the-docs

# URL y Baseurl para TU dominio
# Esto es lo que soluciona el problema de CSS
url: "https://sujetxscriticxs.info"
baseurl: ""

# Puedes mantener los links auxiliares si quieres
aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
