# Título y descripción de TU sitio
title: Sujetxs Criticxs 
description: arte contemporáneo en tiempos de múltiples crisis

# Tema
theme: just-the-docs
color_scheme: custom
color_scheme: lato-theme

# URL y Baseurl para TU dominio
# Esto es lo que soluciona el problema de CSS
url: "https://sujetxscriticxs.info"
baseurl: ""

# Puedes mantener los links auxiliares si quieres
aux_links:

# Añade este bloque al final del archivo
callouts:
  note:
    title:
    color: purple
  warning:
    title: Advertencia
    color: red
  highlight:
    color: yellow
